server:
  port: 8080
  servlet:
    context-path: /blog-facade
spring:
  application:
    name: blog-facade


  data:
    mongodb:
      uri: mongodb://localhost:27017/blog

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
