eureka:
  client:
    service-url:
      # 单节点的注册中心
      defaultZone: http://127.0.0.1:5001/eureka/
    # 不向注册中心注册自己
    # register-with-eureka: false
  server:
    # eureka的自我保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000

  instance:
    instance-id: mopsz-cloud-eureka
    prefer-ip-address: true